# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Whit Richardson
description: "Whit Richardson's personal website"
url:              https://whit.fyi
baseurl:          /


author:
  name:           'Whit Richardson'
  url:            https://twitter.com/whit_richardson

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
